version : '3'

services:
 nginx:
  image: nginx:latest
  ports:
   - '80:80'
  volumes:
   - ./nginx:/etc/nginx/conf.d
   - ./logs/nginx:/var/log/nginx
   - ./wordpress:/var/www/html
  depends_on:
   - wordpress
  restart: always
 mysql:
  image: mariadb
  volumes:
   - ./db-data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=${pass}
  restart: always
 wordpress:
  image: wordpress:4.7.1-php7.0-fpm
  volumes:
   - ./wordpress:/var/www/html
  environment:
   - WORDPRESS_DB_NAME=wpdb
   - WORDPRESS_TABLE_PREFIX=wp_
   - WORDPRESS_DB_HOST=mysql
   - WORDPRESS_DB_PASSWORD=${pass}
  depends_on:
   - mysql
  restart: always
